# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/HIL/HIL.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HIL || ORIG_REF_NAME==HIL} -quiet] -quiet

# IP: bd/HIL/ip/HIL_HIL_0_0/HIL_HIL_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HIL_HIL_0_0 || ORIG_REF_NAME==HIL_HIL_0_0} -quiet] -quiet

# IP: bd/HIL/ip/HIL_processing_system7_0_0/HIL_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HIL_processing_system7_0_0 || ORIG_REF_NAME==HIL_processing_system7_0_0} -quiet] -quiet

# IP: bd/HIL/ip/HIL_ps7_0_axi_periph_0/HIL_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HIL_ps7_0_axi_periph_0 || ORIG_REF_NAME==HIL_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/HIL/ip/HIL_rst_ps7_0_49M_0/HIL_rst_ps7_0_49M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HIL_rst_ps7_0_49M_0 || ORIG_REF_NAME==HIL_rst_ps7_0_49M_0} -quiet] -quiet

# IP: bd/HIL/ip/HIL_auto_pc_0/HIL_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HIL_auto_pc_0 || ORIG_REF_NAME==HIL_auto_pc_0} -quiet] -quiet

# XDC: /home/quim/UPC/STR/Projecte_Final/projecte_final_STR/projecte_final_STR.gen/sources_1/bd/HIL/HIL_ooc.xdc
