# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/quim/UPC/STR/Projecte_Final/projecte_final_STR/projecte_final_STR.srcs/sources_1/bd/HIL/ip/HIL_rst_ps7_0_49M_0/HIL_rst_ps7_0_49M_0.xci
# IP: The module: 'HIL_rst_ps7_0_49M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/quim/UPC/STR/Projecte_Final/projecte_final_STR/projecte_final_STR.gen/sources_1/bd/HIL/ip/HIL_rst_ps7_0_49M_0/HIL_rst_ps7_0_49M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'HIL_rst_ps7_0_49M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/quim/UPC/STR/Projecte_Final/projecte_final_STR/projecte_final_STR.gen/sources_1/bd/HIL/ip/HIL_rst_ps7_0_49M_0/HIL_rst_ps7_0_49M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'HIL_rst_ps7_0_49M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/quim/UPC/STR/Projecte_Final/projecte_final_STR/projecte_final_STR.gen/sources_1/bd/HIL/ip/HIL_rst_ps7_0_49M_0/HIL_rst_ps7_0_49M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'HIL_rst_ps7_0_49M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/quim/UPC/STR/Projecte_Final/projecte_final_STR/projecte_final_STR.srcs/sources_1/bd/HIL/ip/HIL_rst_ps7_0_49M_0/HIL_rst_ps7_0_49M_0.xci
# IP: The module: 'HIL_rst_ps7_0_49M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/quim/UPC/STR/Projecte_Final/projecte_final_STR/projecte_final_STR.gen/sources_1/bd/HIL/ip/HIL_rst_ps7_0_49M_0/HIL_rst_ps7_0_49M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'HIL_rst_ps7_0_49M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/quim/UPC/STR/Projecte_Final/projecte_final_STR/projecte_final_STR.gen/sources_1/bd/HIL/ip/HIL_rst_ps7_0_49M_0/HIL_rst_ps7_0_49M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'HIL_rst_ps7_0_49M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/quim/UPC/STR/Projecte_Final/projecte_final_STR/projecte_final_STR.gen/sources_1/bd/HIL/ip/HIL_rst_ps7_0_49M_0/HIL_rst_ps7_0_49M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'HIL_rst_ps7_0_49M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
