-- -------------------------------------------------------------
-- 
-- File Name: /home/quim/UPC/STR/Projecte_Final/codegen/HIL/hdlsrc/HIL_fixpt.vhd
-- Created: 2021-05-25 18:06:54
-- 
-- Generated by MATLAB 9.10, MATLAB Coder 5.2 and HDL Coder 3.18
-- 
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Design base rate: 1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: HIL_fixpt
-- Source Path: HIL_fixpt
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.HIL_fixpt_pkg.ALL;

ENTITY HIL_fixpt IS
  PORT( xin                               :   IN    vector_of_std_logic_vector14(0 TO 1);  -- ufix14_E10 [2]
        u                                 :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        x                                 :   OUT   vector_of_std_logic_vector14(0 TO 1)  -- ufix14_E10 [2]
        );
END HIL_fixpt;


ARCHITECTURE rtl OF HIL_fixpt IS

  -- Constants
  CONSTANT a0                             : vector_of_signed14(0 TO 3) := 
    (to_signed(16#0FFF#, 14), to_signed(-16#0009#, 14), to_signed(16#0028#, 14), to_signed(16#0FFD#, 14));  -- sfix14 [4]
  CONSTANT b0                             : vector_of_unsigned14(0 TO 1) := 
    (to_unsigned(16#0029#, 14), to_unsigned(16#20C2#, 14));  -- ufix14 [2]

  -- Signals
  SIGNAL xin_unsigned                     : vector_of_unsigned14(0 TO 1);  -- ufix14_E10 [2]
  SIGNAL u_unsigned                       : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL x_tmp                            : vector_of_unsigned14(0 TO 1);  -- ufix14_E10 [2]

BEGIN
  outputgen1: FOR k1 IN 0 TO 1 GENERATE
    xin_unsigned(k1) <= unsigned(xin(k1));
  END GENERATE;

  u_unsigned <= unsigned(u);

  HIL_fixpt_1_output : PROCESS (u_unsigned, xin_unsigned)
    VARIABLE c : vector_of_signed29(0 TO 1);
    VARIABLE add_cast : vector_of_signed52(0 TO 1);
    VARIABLE mul_temp : vector_of_unsigned46(0 TO 1);
    VARIABLE add_cast_0 : vector_of_signed52(0 TO 1);
    VARIABLE add_temp : vector_of_signed52(0 TO 1);
    VARIABLE add_cast_1 : vector_of_signed30(0 TO 1);
    VARIABLE add_cast_2 : vector_of_signed64(0 TO 1);
    VARIABLE cast : vector_of_signed15(0 TO 1);
    VARIABLE mul_temp_0 : vector_of_signed29(0 TO 1);
    VARIABLE add_cast_3 : vector_of_signed28(0 TO 1);
    VARIABLE add_cast_4 : vector_of_signed30(0 TO 1);
    VARIABLE add_temp_0 : vector_of_signed30(0 TO 1);
  BEGIN
    --HDL code generation from MATLAB function: HIL_fixpt
    --%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    --                                                                          %
    --          Generated by MATLAB 9.10 and Fixed-Point Designer 7.2           %
    --                                                                          %
    --%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    FOR l IN 0 TO 1 LOOP
      c(l) := to_signed(16#00000000#, 29);

      FOR k IN 0 TO 1 LOOP
        add_cast_1(k) := resize(c(l), 30);
        add_cast_2(k) := resize(to_signed(k, 32) & '0', 64);
        cast(k) := signed(resize(xin_unsigned(k), 15));
        mul_temp_0(k) := a0(to_integer(to_signed(l, 32) + resize(add_cast_2(k), 32))) * cast(k);
        add_cast_3(k) := mul_temp_0(k)(27 DOWNTO 0);
        add_cast_4(k) := resize(add_cast_3(k), 30);
        add_temp_0(k) := add_cast_1(k) + add_cast_4(k);
        c(l) := add_temp_0(k)(28 DOWNTO 0);
      END LOOP;

      add_cast(l) := resize(c(l) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 52);
      mul_temp(l) := u_unsigned * b0(l);
      add_cast_0(l) := signed(resize(mul_temp(l), 52));
      add_temp(l) := add_cast(l) + add_cast_0(l);
      x_tmp(l) <= unsigned(add_temp(l)(46 DOWNTO 33));
    END LOOP;

  END PROCESS HIL_fixpt_1_output;


  outputgen: FOR k1 IN 0 TO 1 GENERATE
    x(k1) <= std_logic_vector(x_tmp(k1));
  END GENERATE;

END rtl;

